name: AudioSpectrum
main: io.github.norbipeti.audiospectrum.PluginMain
version: 4.0
commands:
 barcount:
     usage: Please give a number between 0 and 16.
 singlemap:
 play:
   aliases: [playsong, playmusic]
 stopplay:
   aliases: [stopsong, stopmusic]